apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "d2m.fullname" . }}-kubedoom
  labels:
    app: kubedoom
  {{- include "d2m.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubedoom.replicas }}
  selector:
    matchLabels:
      app: kubedoom
    {{- include "d2m.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: kubedoom
      {{- include "d2m.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: {{ quote .Values.kubedoom.kubedoom.env.namespace }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.kubedoom.kubedoom.image.repository }}:{{ .Values.kubedoom.kubedoom.image.tag
          | default .Chart.AppVersion }}
        name: kubedoom
        ports:
        - containerPort: 5900
          name: vnc-server
        resources: {}
      - env:
        - name: AUTOCONNECT
          value: {{ quote .Values.kubedoom.novnc.env.autoconnect }}
        - name: VNC_PASSWORD
          value: {{ quote .Values.kubedoom.novnc.env.vncPassword }}
        - name: VNC_SERVER
          value: {{ quote .Values.kubedoom.novnc.env.vncServer }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.kubedoom.novnc.image.repository }}:{{ .Values.kubedoom.novnc.image.tag
          | default .Chart.AppVersion }}
        name: novnc
        ports:
        - containerPort: 6080
          name: vnc-client
        resources: {}
      hostNetwork: true
      serviceAccountName: {{ include "d2m.fullname" . }}-kubedoom
