apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "d2m.fullname" . }}-kubedoom
  labels:
  {{- include "d2m.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kubedoom.serviceAccount.annotations | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "d2m.fullname" . }}-kubedoom
  labels:
  {{- include "d2m.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: '{{ include "d2m.fullname" . }}-kubedoom'
  namespace: '{{ .Release.Namespace }}'
