---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubedoom
  name: kubedoom
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - image: ghcr.io/storax/kubedoom:latest
          env:
            - name: NAMESPACE
              value: default
          name: kubedoom
          ports:
            - containerPort: 5900
              name: vnc-server
        - image: bonigarcia/novnc:1.2.0
          env:
            - name: AUTOCONNECT
              value: 'true'
            - name: VNC_PASSWORD
              value: idbehold
            - name: VNC_SERVER
              value: localhost:5900
          name: novnc
          ports:
            - containerPort: 6080
              name: vnc-client
